config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end



  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div class="conteiner">
<h2>Editing Book</h2>



<% if @book.errors.any? %>
  <div class="errors-message"><%= @book.errors.count %> errors prohibited this book from being saved:</div>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>


<div>
  <%= f.submit 'Update Book' %>
</div>
<div class="button-button">
  <%= link_to "Show", book_path(@book) %>
  |
  <%= link_to "Back", books_path %>
</div>

<% end %>
</div>

app/views/books/index.html.erb
<div class="conteiner">
<h1>Books</h1>

  <table>
    <thead>
     <tr>
      <th class="top-title">Title  </th>
      <th class="top-body">Body</th>
      <th colspan="3"></th>
     </tr>
   </thead>
   <tbody>
    <% @books.each do |book| %>
   <tr>
    <td><%=  book.title %></td>
    <td><%= book.body %></td>
    
    <td>
     <div class="button-button show">
     <%= link_to "Show", book_path(book) %>
     </div>
    </td>
    <td>
     <div class="button-button show">
     <%= link_to "Edit", edit_book_path(book) %>
     </div>
    </td>
    <td>
     <div class="button-button show">
     <%= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "本当に削除しますか？" %>
     </div>
    </td>
   </tr>
    <% end %>
   </tbody>
 </table>


<h3 class="newbook">New book</h3>
<% if @book.errors.any? %>
 <div class="errors-message"><%= @book.errors.count %>errors prohibited this book from being saved:</div>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book , url: '/books', method: :post do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
	<div>
  <%= f.submit 'Create Book' %>
  </div>
<% end %>
</div>

app/views/books/show.html.erb
<div class="conteiner">
<p class="text-show">
  <strong>Title: </strong><%= @book.title %>
</p>

<p class="text-show">
  <strong>Body: </strong><%= @book.body %>
</p>


<div class="button-button">
<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
</div>
</div>

app/views/homes/top.html.erb
<div class="conteiner">
<h1>ようこそ Bookers へ！</h1>
<p class="top-text">Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p class="top-text">印象を共有し交換することができます</p>
</p>
<div class="start-button">
<%= link_to "Start", books_path, class: "custom-link" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>